// Code generated by veduta schema-gen from assets/schemas/architecture.schema.json. DO NOT EDIT.

package schema

import (
	"math"
	"regexp"
	"strconv"
	"unicode/utf8"

	"github.com/ZONO33LHD/archy-go/internal/diag"
)

var (
	rePat0 = regexp.MustCompile("^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$")
)

// ValidateArchitecture は architecture IR の汎用デコード結果 (any) をスキーマ検証する。
func ValidateArchitecture(v any) diag.List {
	var ds diag.List
	vArchitectureRoot("", v, &ds)
	return ds
}

// vArchitectureRoot は IR 文書のルート を検証する。
func vArchitectureRoot(p string, v any, ds *diag.List) {
	obj1, ok := v.(map[string]any)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "オブジェクトが必要です", "値を { } 形式のオブジェクトにする")
		return
	}
	for _, k2 := range sortedKeys(obj1) {
		switch k2 {
		case "boundaries", "cards", "components", "connections", "diagram_type", "meta", "schema_version":
		default:
			addSchemaDiag(ds, "schema/unknown-field", p+"/"+ptrEscape(k2), "未知のフィールドです", "フィールドを削除する", "スキーマで定義された名前に修正する")
		}
	}
	if _, ok := obj1["schema_version"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'schema_version' がありません", "'schema_version' フィールドを追加する")
	}
	if _, ok := obj1["diagram_type"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'diagram_type' がありません", "'diagram_type' フィールドを追加する")
	}
	if _, ok := obj1["meta"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'meta' がありません", "'meta' フィールドを追加する")
	}
	if _, ok := obj1["components"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'components' がありません", "'components' フィールドを追加する")
	}
	if pv3, ok := obj1["boundaries"]; ok {
		a4, ok := pv3.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/boundaries", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a4) > 100 {
				addSchemaDiag(ds, "schema/items", p+"/boundaries", "要素数が上限を超えています (最大 100、実際 "+strconv.Itoa(len(a4))+")", "要素を 100 個以内に減らす")
			}
			lim7 := len(a4)
			if lim7 > 100 {
				lim7 = 100
			}
			for i5 := 0; i5 < lim7; i5++ {
				if ds.AtCap() {
					break
				}
				e6 := a4[i5]
				vDefBoundary(p+"/boundaries"+"/"+strconv.Itoa(i5), e6, ds)
			}
		}
	}
	if pv8, ok := obj1["cards"]; ok {
		a9, ok := pv8.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/cards", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a9) > 20 {
				addSchemaDiag(ds, "schema/items", p+"/cards", "要素数が上限を超えています (最大 20、実際 "+strconv.Itoa(len(a9))+")", "要素を 20 個以内に減らす")
			}
			lim12 := len(a9)
			if lim12 > 20 {
				lim12 = 20
			}
			for i10 := 0; i10 < lim12; i10++ {
				if ds.AtCap() {
					break
				}
				e11 := a9[i10]
				vDefCard(p+"/cards"+"/"+strconv.Itoa(i10), e11, ds)
			}
		}
	}
	if pv13, ok := obj1["components"]; ok {
		a14, ok := pv13.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/components", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a14) < 1 {
				addSchemaDiag(ds, "schema/items", p+"/components", "要素数が不足しています (最小 1、実際 "+strconv.Itoa(len(a14))+")", "要素を 1 個以上にする")
			}
			if len(a14) > 500 {
				addSchemaDiag(ds, "schema/items", p+"/components", "要素数が上限を超えています (最大 500、実際 "+strconv.Itoa(len(a14))+")", "要素を 500 個以内に減らす")
			}
			lim17 := len(a14)
			if lim17 > 500 {
				lim17 = 500
			}
			for i15 := 0; i15 < lim17; i15++ {
				if ds.AtCap() {
					break
				}
				e16 := a14[i15]
				vDefComponent(p+"/components"+"/"+strconv.Itoa(i15), e16, ds)
			}
		}
	}
	if pv18, ok := obj1["connections"]; ok {
		a19, ok := pv18.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/connections", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a19) > 2000 {
				addSchemaDiag(ds, "schema/items", p+"/connections", "要素数が上限を超えています (最大 2000、実際 "+strconv.Itoa(len(a19))+")", "要素を 2000 個以内に減らす")
			}
			lim22 := len(a19)
			if lim22 > 2000 {
				lim22 = 2000
			}
			for i20 := 0; i20 < lim22; i20++ {
				if ds.AtCap() {
					break
				}
				e21 := a19[i20]
				vDefConnection(p+"/connections"+"/"+strconv.Itoa(i20), e21, ds)
			}
		}
	}
	if pv23, ok := obj1["diagram_type"]; ok {
		s24, ok := pv23.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/diagram_type", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			switch s24 {
			case "architecture":
			default:
				addSchemaDiag(ds, "schema/enum", p+"/diagram_type", "許可されない値です (許可: architecture)", "値を次のいずれかに変更する: architecture")
			}
		}
	}
	if pv25, ok := obj1["meta"]; ok {
		vDefMeta(p+"/meta", pv25, ds)
	}
	if pv26, ok := obj1["schema_version"]; ok {
		f27, ok := pv26.(float64)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/schema_version", "数値が必要です", "値を数値リテラルにする")
		} else {
			if f27 != math.Trunc(f27) {
				addSchemaDiag(ds, "schema/type", p+"/schema_version", "整数が必要です", "小数部を持たない整数値にする")
			}
			if f27 < 1 {
				addSchemaDiag(ds, "schema/range", p+"/schema_version", "数値が下限 1 を下回っています", "値を 1 以上にする")
			}
			if f27 > 1 {
				addSchemaDiag(ds, "schema/range", p+"/schema_version", "数値が上限 1 を超えています", "値を 1 以下にする")
			}
		}
	}
}

// vDefBoundary は $defs/boundary を検証する。
func vDefBoundary(p string, v any, ds *diag.List) {
	obj28, ok := v.(map[string]any)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "オブジェクトが必要です", "値を { } 形式のオブジェクトにする")
		return
	}
	for _, k29 := range sortedKeys(obj28) {
		switch k29 {
		case "kind", "label", "wraps":
		default:
			addSchemaDiag(ds, "schema/unknown-field", p+"/"+ptrEscape(k29), "未知のフィールドです", "フィールドを削除する", "スキーマで定義された名前に修正する")
		}
	}
	if _, ok := obj28["kind"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'kind' がありません", "'kind' フィールドを追加する")
	}
	if _, ok := obj28["label"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'label' がありません", "'label' フィールドを追加する")
	}
	if _, ok := obj28["wraps"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'wraps' がありません", "'wraps' フィールドを追加する")
	}
	if pv30, ok := obj28["kind"]; ok {
		s31, ok := pv30.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/kind", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			switch s31 {
			case "region", "zone", "vpc", "subnet", "cluster", "network", "security", "trust":
			default:
				addSchemaDiag(ds, "schema/enum", p+"/kind", "許可されない値です (許可: region | zone | vpc | subnet | cluster | network | security | trust)", "値を次のいずれかに変更する: region | zone | vpc | subnet | cluster | network | security | trust")
			}
		}
	}
	if pv32, ok := obj28["label"]; ok {
		s33, ok := pv32.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/label", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n34 := utf8.RuneCountInString(s33)
			if n34 < 1 {
				addSchemaDiag(ds, "schema/length", p+"/label", "文字数が不足しています (最小 1 コードポイント、実際 "+strconv.Itoa(n34)+")", "1 文字以上の値にする")
			}
			if n34 > 200 {
				addSchemaDiag(ds, "schema/length", p+"/label", "文字数が上限を超えています (最大 200 コードポイント、実際 "+strconv.Itoa(n34)+")", "意味を保ったまま 200 文字以内に短縮する")
			}
		}
	}
	if pv35, ok := obj28["wraps"]; ok {
		a36, ok := pv35.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/wraps", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a36) < 1 {
				addSchemaDiag(ds, "schema/items", p+"/wraps", "要素数が不足しています (最小 1、実際 "+strconv.Itoa(len(a36))+")", "要素を 1 個以上にする")
			}
			if len(a36) > 100 {
				addSchemaDiag(ds, "schema/items", p+"/wraps", "要素数が上限を超えています (最大 100、実際 "+strconv.Itoa(len(a36))+")", "要素を 100 個以内に減らす")
			}
			lim39 := len(a36)
			if lim39 > 100 {
				lim39 = 100
			}
			for i37 := 0; i37 < lim39; i37++ {
				if ds.AtCap() {
					break
				}
				e38 := a36[i37]
				vDefId(p+"/wraps"+"/"+strconv.Itoa(i37), e38, ds)
			}
		}
	}
}

// vDefCard は $defs/card を検証する。
func vDefCard(p string, v any, ds *diag.List) {
	obj40, ok := v.(map[string]any)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "オブジェクトが必要です", "値を { } 形式のオブジェクトにする")
		return
	}
	for _, k41 := range sortedKeys(obj40) {
		switch k41 {
		case "dot", "items", "title":
		default:
			addSchemaDiag(ds, "schema/unknown-field", p+"/"+ptrEscape(k41), "未知のフィールドです", "フィールドを削除する", "スキーマで定義された名前に修正する")
		}
	}
	if _, ok := obj40["title"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'title' がありません", "'title' フィールドを追加する")
	}
	if _, ok := obj40["items"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'items' がありません", "'items' フィールドを追加する")
	}
	if pv42, ok := obj40["dot"]; ok {
		s43, ok := pv42.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/dot", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			switch s43 {
			case "cyan", "blue", "green", "amber", "red", "purple", "gray":
			default:
				addSchemaDiag(ds, "schema/enum", p+"/dot", "許可されない値です (許可: cyan | blue | green | amber | red | purple | gray)", "値を次のいずれかに変更する: cyan | blue | green | amber | red | purple | gray")
			}
		}
	}
	if pv44, ok := obj40["items"]; ok {
		a45, ok := pv44.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/items", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a45) < 1 {
				addSchemaDiag(ds, "schema/items", p+"/items", "要素数が不足しています (最小 1、実際 "+strconv.Itoa(len(a45))+")", "要素を 1 個以上にする")
			}
			if len(a45) > 10 {
				addSchemaDiag(ds, "schema/items", p+"/items", "要素数が上限を超えています (最大 10、実際 "+strconv.Itoa(len(a45))+")", "要素を 10 個以内に減らす")
			}
			lim48 := len(a45)
			if lim48 > 10 {
				lim48 = 10
			}
			for i46 := 0; i46 < lim48; i46++ {
				if ds.AtCap() {
					break
				}
				e47 := a45[i46]
				s49, ok := e47.(string)
				if !ok {
					addSchemaDiag(ds, "schema/type", p+"/items"+"/"+strconv.Itoa(i46), "文字列が必要です", "値を \"...\" 形式の文字列にする")
				} else {
					n50 := utf8.RuneCountInString(s49)
					if n50 < 1 {
						addSchemaDiag(ds, "schema/length", p+"/items"+"/"+strconv.Itoa(i46), "文字数が不足しています (最小 1 コードポイント、実際 "+strconv.Itoa(n50)+")", "1 文字以上の値にする")
					}
					if n50 > 200 {
						addSchemaDiag(ds, "schema/length", p+"/items"+"/"+strconv.Itoa(i46), "文字数が上限を超えています (最大 200 コードポイント、実際 "+strconv.Itoa(n50)+")", "意味を保ったまま 200 文字以内に短縮する")
					}
				}
			}
		}
	}
	if pv51, ok := obj40["title"]; ok {
		s52, ok := pv51.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/title", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n53 := utf8.RuneCountInString(s52)
			if n53 < 1 {
				addSchemaDiag(ds, "schema/length", p+"/title", "文字数が不足しています (最小 1 コードポイント、実際 "+strconv.Itoa(n53)+")", "1 文字以上の値にする")
			}
			if n53 > 200 {
				addSchemaDiag(ds, "schema/length", p+"/title", "文字数が上限を超えています (最大 200 コードポイント、実際 "+strconv.Itoa(n53)+")", "意味を保ったまま 200 文字以内に短縮する")
			}
		}
	}
}

// vDefComponent は $defs/component を検証する。
func vDefComponent(p string, v any, ds *diag.List) {
	obj54, ok := v.(map[string]any)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "オブジェクトが必要です", "値を { } 形式のオブジェクトにする")
		return
	}
	for _, k55 := range sortedKeys(obj54) {
		switch k55 {
		case "id", "label", "pos", "size", "sublabel", "tag", "type":
		default:
			addSchemaDiag(ds, "schema/unknown-field", p+"/"+ptrEscape(k55), "未知のフィールドです", "フィールドを削除する", "スキーマで定義された名前に修正する")
		}
	}
	if _, ok := obj54["id"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'id' がありません", "'id' フィールドを追加する")
	}
	if _, ok := obj54["type"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'type' がありません", "'type' フィールドを追加する")
	}
	if _, ok := obj54["label"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'label' がありません", "'label' フィールドを追加する")
	}
	if _, ok := obj54["pos"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'pos' がありません", "'pos' フィールドを追加する")
	}
	if _, ok := obj54["size"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'size' がありません", "'size' フィールドを追加する")
	}
	if pv56, ok := obj54["id"]; ok {
		vDefId(p+"/id", pv56, ds)
	}
	if pv57, ok := obj54["label"]; ok {
		s58, ok := pv57.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/label", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n59 := utf8.RuneCountInString(s58)
			if n59 < 1 {
				addSchemaDiag(ds, "schema/length", p+"/label", "文字数が不足しています (最小 1 コードポイント、実際 "+strconv.Itoa(n59)+")", "1 文字以上の値にする")
			}
			if n59 > 200 {
				addSchemaDiag(ds, "schema/length", p+"/label", "文字数が上限を超えています (最大 200 コードポイント、実際 "+strconv.Itoa(n59)+")", "意味を保ったまま 200 文字以内に短縮する")
			}
		}
	}
	if pv60, ok := obj54["pos"]; ok {
		vDefVec2(p+"/pos", pv60, ds)
	}
	if pv61, ok := obj54["size"]; ok {
		vDefSize2(p+"/size", pv61, ds)
	}
	if pv62, ok := obj54["sublabel"]; ok {
		s63, ok := pv62.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/sublabel", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n64 := utf8.RuneCountInString(s63)
			if n64 > 200 {
				addSchemaDiag(ds, "schema/length", p+"/sublabel", "文字数が上限を超えています (最大 200 コードポイント、実際 "+strconv.Itoa(n64)+")", "意味を保ったまま 200 文字以内に短縮する")
			}
		}
	}
	if pv65, ok := obj54["tag"]; ok {
		s66, ok := pv65.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/tag", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n67 := utf8.RuneCountInString(s66)
			if n67 > 80 {
				addSchemaDiag(ds, "schema/length", p+"/tag", "文字数が上限を超えています (最大 80 コードポイント、実際 "+strconv.Itoa(n67)+")", "意味を保ったまま 80 文字以内に短縮する")
			}
		}
	}
	if pv68, ok := obj54["type"]; ok {
		s69, ok := pv68.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/type", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			switch s69 {
			case "frontend", "backend", "database", "cloud", "security", "messagebus", "external":
			default:
				addSchemaDiag(ds, "schema/enum", p+"/type", "許可されない値です (許可: frontend | backend | database | cloud | security | messagebus | external)", "値を次のいずれかに変更する: frontend | backend | database | cloud | security | messagebus | external")
			}
		}
	}
}

// vDefConnection は $defs/connection を検証する。
func vDefConnection(p string, v any, ds *diag.List) {
	obj70, ok := v.(map[string]any)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "オブジェクトが必要です", "値を { } 形式のオブジェクトにする")
		return
	}
	for _, k71 := range sortedKeys(obj70) {
		switch k71 {
		case "channelX", "channelY", "from", "fromSide", "id", "label", "labelAt", "labelDy", "to", "toSide", "variant", "via":
		default:
			addSchemaDiag(ds, "schema/unknown-field", p+"/"+ptrEscape(k71), "未知のフィールドです", "フィールドを削除する", "スキーマで定義された名前に修正する")
		}
	}
	if _, ok := obj70["id"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'id' がありません", "'id' フィールドを追加する")
	}
	if _, ok := obj70["from"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'from' がありません", "'from' フィールドを追加する")
	}
	if _, ok := obj70["to"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'to' がありません", "'to' フィールドを追加する")
	}
	if pv72, ok := obj70["channelX"]; ok {
		vDefCoord(p+"/channelX", pv72, ds)
	}
	if pv73, ok := obj70["channelY"]; ok {
		vDefCoord(p+"/channelY", pv73, ds)
	}
	if pv74, ok := obj70["from"]; ok {
		vDefId(p+"/from", pv74, ds)
	}
	if pv75, ok := obj70["fromSide"]; ok {
		vDefSide(p+"/fromSide", pv75, ds)
	}
	if pv76, ok := obj70["id"]; ok {
		vDefId(p+"/id", pv76, ds)
	}
	if pv77, ok := obj70["label"]; ok {
		s78, ok := pv77.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/label", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n79 := utf8.RuneCountInString(s78)
			if n79 > 200 {
				addSchemaDiag(ds, "schema/length", p+"/label", "文字数が上限を超えています (最大 200 コードポイント、実際 "+strconv.Itoa(n79)+")", "意味を保ったまま 200 文字以内に短縮する")
			}
		}
	}
	if pv80, ok := obj70["labelAt"]; ok {
		f81, ok := pv80.(float64)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/labelAt", "数値が必要です", "値を数値リテラルにする")
		} else {
			if f81 < 0 {
				addSchemaDiag(ds, "schema/range", p+"/labelAt", "数値が下限 0 を下回っています", "値を 0 以上にする")
			}
			if f81 > 1 {
				addSchemaDiag(ds, "schema/range", p+"/labelAt", "数値が上限 1 を超えています", "値を 1 以下にする")
			}
		}
	}
	if pv82, ok := obj70["labelDy"]; ok {
		f83, ok := pv82.(float64)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/labelDy", "数値が必要です", "値を数値リテラルにする")
		} else {
			if f83 < -500 {
				addSchemaDiag(ds, "schema/range", p+"/labelDy", "数値が下限 -500 を下回っています", "値を -500 以上にする")
			}
			if f83 > 500 {
				addSchemaDiag(ds, "schema/range", p+"/labelDy", "数値が上限 500 を超えています", "値を 500 以下にする")
			}
		}
	}
	if pv84, ok := obj70["to"]; ok {
		vDefId(p+"/to", pv84, ds)
	}
	if pv85, ok := obj70["toSide"]; ok {
		vDefSide(p+"/toSide", pv85, ds)
	}
	if pv86, ok := obj70["variant"]; ok {
		s87, ok := pv86.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/variant", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			switch s87 {
			case "default", "emphasis", "security", "dashed":
			default:
				addSchemaDiag(ds, "schema/enum", p+"/variant", "許可されない値です (許可: default | emphasis | security | dashed)", "値を次のいずれかに変更する: default | emphasis | security | dashed")
			}
		}
	}
	if pv88, ok := obj70["via"]; ok {
		a89, ok := pv88.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/via", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a89) < 1 {
				addSchemaDiag(ds, "schema/items", p+"/via", "要素数が不足しています (最小 1、実際 "+strconv.Itoa(len(a89))+")", "要素を 1 個以上にする")
			}
			if len(a89) > 16 {
				addSchemaDiag(ds, "schema/items", p+"/via", "要素数が上限を超えています (最大 16、実際 "+strconv.Itoa(len(a89))+")", "要素を 16 個以内に減らす")
			}
			lim92 := len(a89)
			if lim92 > 16 {
				lim92 = 16
			}
			for i90 := 0; i90 < lim92; i90++ {
				if ds.AtCap() {
					break
				}
				e91 := a89[i90]
				vDefVec2(p+"/via"+"/"+strconv.Itoa(i90), e91, ds)
			}
		}
	}
}

// vDefCoord は $defs/coord を検証する。
func vDefCoord(p string, v any, ds *diag.List) {
	f93, ok := v.(float64)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "数値が必要です", "値を数値リテラルにする")
	} else {
		if f93 < -1e+06 {
			addSchemaDiag(ds, "schema/range", p, "数値が下限 -1000000 を下回っています", "値を -1000000 以上にする")
		}
		if f93 > 1e+06 {
			addSchemaDiag(ds, "schema/range", p, "数値が上限 1000000 を超えています", "値を 1000000 以下にする")
		}
	}
}

// vDefId は $defs/id を検証する。
func vDefId(p string, v any, ds *diag.List) {
	s94, ok := v.(string)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "文字列が必要です", "値を \"...\" 形式の文字列にする")
	} else {
		if !rePat0.MatchString(s94) {
			addSchemaDiag(ds, "schema/pattern", p, "形式が不正です (許可パターン: ^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$)", "英数字で始まり、英数字・'_'・'-' のみ 64 文字以内の値に変更する")
		}
	}
}

// vDefMeta は $defs/meta を検証する。
func vDefMeta(p string, v any, ds *diag.List) {
	obj95, ok := v.(map[string]any)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "オブジェクトが必要です", "値を { } 形式のオブジェクトにする")
		return
	}
	for _, k96 := range sortedKeys(obj95) {
		switch k96 {
		case "animation", "locale", "output", "quality_profile", "title", "viewBox", "views", "visual_preset":
		default:
			addSchemaDiag(ds, "schema/unknown-field", p+"/"+ptrEscape(k96), "未知のフィールドです", "フィールドを削除する", "スキーマで定義された名前に修正する")
		}
	}
	if _, ok := obj95["title"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'title' がありません", "'title' フィールドを追加する")
	}
	if pv97, ok := obj95["animation"]; ok {
		s98, ok := pv97.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/animation", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			switch s98 {
			case "trace":
			default:
				addSchemaDiag(ds, "schema/enum", p+"/animation", "許可されない値です (許可: trace)", "値を次のいずれかに変更する: trace")
			}
		}
	}
	if pv99, ok := obj95["locale"]; ok {
		s100, ok := pv99.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/locale", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			switch s100 {
			case "en", "ja", "zh-CN":
			default:
				addSchemaDiag(ds, "schema/enum", p+"/locale", "許可されない値です (許可: en | ja | zh-CN)", "値を次のいずれかに変更する: en | ja | zh-CN")
			}
		}
	}
	if pv101, ok := obj95["output"]; ok {
		s102, ok := pv101.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/output", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n103 := utf8.RuneCountInString(s102)
			if n103 < 6 {
				addSchemaDiag(ds, "schema/length", p+"/output", "文字数が不足しています (最小 6 コードポイント、実際 "+strconv.Itoa(n103)+")", "6 文字以上の値にする")
			}
			if n103 > 300 {
				addSchemaDiag(ds, "schema/length", p+"/output", "文字数が上限を超えています (最大 300 コードポイント、実際 "+strconv.Itoa(n103)+")", "意味を保ったまま 300 文字以内に短縮する")
			}
		}
	}
	if pv104, ok := obj95["quality_profile"]; ok {
		s105, ok := pv104.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/quality_profile", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			switch s105 {
			case "standard", "showcase":
			default:
				addSchemaDiag(ds, "schema/enum", p+"/quality_profile", "許可されない値です (許可: standard | showcase)", "値を次のいずれかに変更する: standard | showcase")
			}
		}
	}
	if pv106, ok := obj95["title"]; ok {
		s107, ok := pv106.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/title", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n108 := utf8.RuneCountInString(s107)
			if n108 < 1 {
				addSchemaDiag(ds, "schema/length", p+"/title", "文字数が不足しています (最小 1 コードポイント、実際 "+strconv.Itoa(n108)+")", "1 文字以上の値にする")
			}
			if n108 > 200 {
				addSchemaDiag(ds, "schema/length", p+"/title", "文字数が上限を超えています (最大 200 コードポイント、実際 "+strconv.Itoa(n108)+")", "意味を保ったまま 200 文字以内に短縮する")
			}
		}
	}
	if pv109, ok := obj95["viewBox"]; ok {
		a110, ok := pv109.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/viewBox", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a110) < 4 {
				addSchemaDiag(ds, "schema/items", p+"/viewBox", "要素数が不足しています (最小 4、実際 "+strconv.Itoa(len(a110))+")", "要素を 4 個以上にする")
			}
			if len(a110) > 4 {
				addSchemaDiag(ds, "schema/items", p+"/viewBox", "要素数が上限を超えています (最大 4、実際 "+strconv.Itoa(len(a110))+")", "要素を 4 個以内に減らす")
			}
			lim113 := len(a110)
			if lim113 > 4 {
				lim113 = 4
			}
			for i111 := 0; i111 < lim113; i111++ {
				if ds.AtCap() {
					break
				}
				e112 := a110[i111]
				vDefCoord(p+"/viewBox"+"/"+strconv.Itoa(i111), e112, ds)
			}
		}
	}
	if pv114, ok := obj95["views"]; ok {
		a115, ok := pv114.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/views", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a115) > 10 {
				addSchemaDiag(ds, "schema/items", p+"/views", "要素数が上限を超えています (最大 10、実際 "+strconv.Itoa(len(a115))+")", "要素を 10 個以内に減らす")
			}
			lim118 := len(a115)
			if lim118 > 10 {
				lim118 = 10
			}
			for i116 := 0; i116 < lim118; i116++ {
				if ds.AtCap() {
					break
				}
				e117 := a115[i116]
				vDefView(p+"/views"+"/"+strconv.Itoa(i116), e117, ds)
			}
		}
	}
	if pv119, ok := obj95["visual_preset"]; ok {
		s120, ok := pv119.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/visual_preset", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			switch s120 {
			case "classic", "signal-flow", "blueprint", "editorial":
			default:
				addSchemaDiag(ds, "schema/enum", p+"/visual_preset", "許可されない値です (許可: classic | signal-flow | blueprint | editorial)", "値を次のいずれかに変更する: classic | signal-flow | blueprint | editorial")
			}
		}
	}
}

// vDefSide は $defs/side を検証する。
func vDefSide(p string, v any, ds *diag.List) {
	s121, ok := v.(string)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "文字列が必要です", "値を \"...\" 形式の文字列にする")
	} else {
		switch s121 {
		case "left", "right", "top", "bottom":
		default:
			addSchemaDiag(ds, "schema/enum", p, "許可されない値です (許可: left | right | top | bottom)", "値を次のいずれかに変更する: left | right | top | bottom")
		}
	}
}

// vDefSize2 は $defs/size2 を検証する。
func vDefSize2(p string, v any, ds *diag.List) {
	a122, ok := v.([]any)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "配列が必要です", "値を [ ] 形式の配列にする")
	} else {
		if len(a122) < 2 {
			addSchemaDiag(ds, "schema/items", p, "要素数が不足しています (最小 2、実際 "+strconv.Itoa(len(a122))+")", "要素を 2 個以上にする")
		}
		if len(a122) > 2 {
			addSchemaDiag(ds, "schema/items", p, "要素数が上限を超えています (最大 2、実際 "+strconv.Itoa(len(a122))+")", "要素を 2 個以内に減らす")
		}
		lim125 := len(a122)
		if lim125 > 2 {
			lim125 = 2
		}
		for i123 := 0; i123 < lim125; i123++ {
			if ds.AtCap() {
				break
			}
			e124 := a122[i123]
			f126, ok := e124.(float64)
			if !ok {
				addSchemaDiag(ds, "schema/type", p+"/"+strconv.Itoa(i123), "数値が必要です", "値を数値リテラルにする")
			} else {
				if f126 < 10 {
					addSchemaDiag(ds, "schema/range", p+"/"+strconv.Itoa(i123), "数値が下限 10 を下回っています", "値を 10 以上にする")
				}
				if f126 > 4000 {
					addSchemaDiag(ds, "schema/range", p+"/"+strconv.Itoa(i123), "数値が上限 4000 を超えています", "値を 4000 以下にする")
				}
			}
		}
	}
}

// vDefVec2 は $defs/vec2 を検証する。
func vDefVec2(p string, v any, ds *diag.List) {
	a127, ok := v.([]any)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "配列が必要です", "値を [ ] 形式の配列にする")
	} else {
		if len(a127) < 2 {
			addSchemaDiag(ds, "schema/items", p, "要素数が不足しています (最小 2、実際 "+strconv.Itoa(len(a127))+")", "要素を 2 個以上にする")
		}
		if len(a127) > 2 {
			addSchemaDiag(ds, "schema/items", p, "要素数が上限を超えています (最大 2、実際 "+strconv.Itoa(len(a127))+")", "要素を 2 個以内に減らす")
		}
		lim130 := len(a127)
		if lim130 > 2 {
			lim130 = 2
		}
		for i128 := 0; i128 < lim130; i128++ {
			if ds.AtCap() {
				break
			}
			e129 := a127[i128]
			vDefCoord(p+"/"+strconv.Itoa(i128), e129, ds)
		}
	}
}

// vDefView は $defs/view を検証する。
func vDefView(p string, v any, ds *diag.List) {
	obj131, ok := v.(map[string]any)
	if !ok {
		addSchemaDiag(ds, "schema/type", p, "オブジェクトが必要です", "値を { } 形式のオブジェクトにする")
		return
	}
	for _, k132 := range sortedKeys(obj131) {
		switch k132 {
		case "focus", "id", "label", "note":
		default:
			addSchemaDiag(ds, "schema/unknown-field", p+"/"+ptrEscape(k132), "未知のフィールドです", "フィールドを削除する", "スキーマで定義された名前に修正する")
		}
	}
	if _, ok := obj131["id"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'id' がありません", "'id' フィールドを追加する")
	}
	if _, ok := obj131["label"]; !ok {
		addSchemaDiag(ds, "schema/required", p, "必須フィールド 'label' がありません", "'label' フィールドを追加する")
	}
	if pv133, ok := obj131["focus"]; ok {
		a134, ok := pv133.([]any)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/focus", "配列が必要です", "値を [ ] 形式の配列にする")
		} else {
			if len(a134) < 1 {
				addSchemaDiag(ds, "schema/items", p+"/focus", "要素数が不足しています (最小 1、実際 "+strconv.Itoa(len(a134))+")", "要素を 1 個以上にする")
			}
			if len(a134) > 50 {
				addSchemaDiag(ds, "schema/items", p+"/focus", "要素数が上限を超えています (最大 50、実際 "+strconv.Itoa(len(a134))+")", "要素を 50 個以内に減らす")
			}
			lim137 := len(a134)
			if lim137 > 50 {
				lim137 = 50
			}
			for i135 := 0; i135 < lim137; i135++ {
				if ds.AtCap() {
					break
				}
				e136 := a134[i135]
				vDefId(p+"/focus"+"/"+strconv.Itoa(i135), e136, ds)
			}
		}
	}
	if pv138, ok := obj131["id"]; ok {
		vDefId(p+"/id", pv138, ds)
	}
	if pv139, ok := obj131["label"]; ok {
		s140, ok := pv139.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/label", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n141 := utf8.RuneCountInString(s140)
			if n141 < 1 {
				addSchemaDiag(ds, "schema/length", p+"/label", "文字数が不足しています (最小 1 コードポイント、実際 "+strconv.Itoa(n141)+")", "1 文字以上の値にする")
			}
			if n141 > 200 {
				addSchemaDiag(ds, "schema/length", p+"/label", "文字数が上限を超えています (最大 200 コードポイント、実際 "+strconv.Itoa(n141)+")", "意味を保ったまま 200 文字以内に短縮する")
			}
		}
	}
	if pv142, ok := obj131["note"]; ok {
		s143, ok := pv142.(string)
		if !ok {
			addSchemaDiag(ds, "schema/type", p+"/note", "文字列が必要です", "値を \"...\" 形式の文字列にする")
		} else {
			n144 := utf8.RuneCountInString(s143)
			if n144 > 500 {
				addSchemaDiag(ds, "schema/length", p+"/note", "文字数が上限を超えています (最大 500 コードポイント、実際 "+strconv.Itoa(n144)+")", "意味を保ったまま 500 文字以内に短縮する")
			}
		}
	}
}
